services:
  - type: web
    name: digit-recognizer
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    build:
      pythonVersion: 3.10.13
